// remember:
// hideOnHome: true  
// hideOnMap: true   

window.__MAP_DATA = {
  nodes: [
    {
      id: "first-post",
      title: "First Post",
      date: "Mar 21, 2026",
      href: "post/first-post",
      type: "post",
    },
    {
      id: "fck-this",
      title: "f*ck this",
      date: "Mar 23, 2026",
      href: "post/f*ck-this",
      type: "post",
    },
    {
      id: "orangedogs",
      title: "Orange dogs and Clark",
      date: "Mar 24, 2026",
      href: "post/orangedogsandclark",
      type: "post",
    },
    {
      id: "cicacai",
      title: "Cicacai cac",
      date: "Mar 24, 2026",
      href: "post/cicacaicac",
      type: "post",
    },
    {
      id: "home-archive",
      title: "home (archive)",
      date: "Apr 2, 2026",
      href: "archives/home-archive",
      type: "post",
    },
    {
      id: "oh-dear",
      title: "oh dear",
      date: "Apr 13, 2026",
      href: "post/oh-dear",
      type: "post",
    },
    {
      id: "are-you-okay",
      title: "are you okay?",
      date: "Apr 10, 2026",
      href: "post/are-you-okay",
      type: "post",
    },
    {
      id: "monetary-worth",
      title: "monetary worth",
      date: "Apr 9, 2026",
      href: "post/monetary-worth",
      type: "post",
    },
    {
      id: "fck-giver",
      title: "f*ck giver",
      date: "Apr 9, 2026",
      href: "post/f*ck-giver",
      type: "post",
    },
    {
      id: "welcome-back",
      title: "welcome back!",
      date: "Jun 4, 2026",
      href: "post/welcome-back",
      type: "post",
    },
    {
      id: "pirates",
      title: "pirates",
      date: "Jun 4, 2026",
      href: "post/pirates",
      type: "post",
    },
    {
      id: "effort",
      title: "effort",
      date: "Jun 4, 2026",
      href: "post/effort",
      type: "post",
    },
    {
      id: "silence",
      title: "silence on our end",
      date: "Jun 5, 2026",
      href: "post/silence-on-our-end",
      type: "post",
    },
    {
      id: "heatstroke",
      title: "heatstroke",
      date: "Jun 9, 2026",
      href: "profmed/pyro/heatstroke",
      type: "post",
      hideOnHome: true,
    },
    {
      id: "i-was-right",
      title: "I was sadly right",
      date: "Jun 10, 2026",
      href: "post/i-was-right",
      type: "post",
    },
    {
      id: "priorities",
      title: "priorities",
      date: "Jun 12, 2026",
      href: "post/priorities",
      type: "post",
    },
    {
      id: "second-thoughts",
      title: "second thoughts",
      date: "Jun 13, 2026",
      href: "post/second-thoughts",
      type: "post",
    },
    {
      id: "profiler",
      title: "profiler",
      date: "Jun 18, 2026",
      href: "post/profiler",
      type: "post",
    },
    {
      id: "servience",
      title: "servience",
      date: "Jun 23, 2026",
      href: "post/servience",
      type: "post",
      hideOnHome: true,
    },
    {
      id: "servility",
      title: "servility",
      date: "Jun 24, 2026",
      href: "post/servility",
      type: "post",
    },
    {
      id: "today",
      title: "today",
      date: "Jun 21, 2026",
      href: "post/today",
      type: "post",
    },
    {
      id: "vindication",
      title: "personal vindication",
      date: "Jun 26, 2026",
      href: "post/personal-vindication",
      type: "post",
    },
    {
      id: "poker",
      title: "poker",
      date: "Jun 27, 2026",
      href: "post/poker",
      type: "post",
    },
    {
      id: "evader",
      title: "evader",
      date: "Jun 28, 2026",
      href: "post/evader",
      type: "post",
    },
    {
      id: "a-storm",
      title: "a storm",
      date: "Jun 28, 2026",
      href: "post/a-storm",
      type: "post",
      hideOnHome: true,
    },
    {
      id: "his-way",
      title: "<span class='i'>his</span> way",
      date: "Jun 29, 2026",
      href: "post/his-way",
      type: "post",
    },
    {
      id: "dreams",
      title: "dreams",
      date: "Jul 2, 2026",
      href: "post/dreams",
      type: "post",
    },
    {
      id: "eye-collector",
      title: "Eye-collector",
      date: "Jun 18, 2026",
      href: "story/eye-collecting-man",
      type: "story",
    },
    {
      id: "protests",
      title: "protests",
      date: "Jun 16, 2026",
      href: "story/protests",
      type: "story",
    },
    {
      id: "action-p1",
      title: "Action: Phase 1",
      date: "Jun 13, 2026",
      href: "story/action-phase-one",
      type: "story",
    },
    {
      id: "what-dregs",
      title: "what are <span class='b'>dregs</span>?",
      date: "Jun 28, 2026",
      href: "dreg/what-is-that",
      type: "dreg",
    },
    {
      id: "mew-gane",
      title: "mew <span class='i'>gane</span>",
      date: "Jun 29, 2026",
      href: "dreg/mew-gane",
      type: "dreg",
    },
    {
      id: "in-shambles",
      title: "in shambles",
      date: "Jun 30, 2026",
      href: "dreg/in-shambles",
      type: "dreg",
    },
    {
      id: "sleep",
      title: "sleep",
      date: "Jul 2, 2026",
      href: "dreg/sleep",
      type: "dreg",
    },
    {
      id: "underscorextwo-tuglemo",
      title: "__tuglemo",
      date: "Jul 2, 2026",
      href: "dreg/underscorextwo-tuglemo",
      type: "dreg",
    },
    {
      id: "tnr",
      title: "tnr",
      date: "Jul 3, 2026",
      href: "dreg/tnr",
      type: "dreg",
    },
    {
      id: "chemicals",
      title: "chemicals",
      date: "Jul 6, 2026",
      href: "dreg/chemicals",
      type: "dreg",
    },
    {
      id: "me-nothing",
      title: "me: nothing",
      date: "Jul 6, 2026",
      href: "post/me-nothing",
      type: "post",
    },
    {
      id: "untitled",
      title: "untitled",
      date: "Jul 6, 2026",
      href: "story/untitled",
      type: "story",
    },
    {
      id: "writeflow",
      title: "writeflow",
      date: "Jul 8, 2026",
      href: "dreg/writeflow",
      type: "dreg",
    },
    {
      id: "familiar-warmth",
      title: "familiar warmth",
      date: "Jul 8, 2026",
      href: "story/familiar-warmth",
      type: "story",
    },
    {
      id: "leveler",
      title: "Leveler",
      date: "Jul 8, 2026",
      href: "story/Leveler",
      type: "story",
    },
    {
      id: "waste",
      title: "waste",
      date: "Jul 9, 2026",
      href: "post/waste",
      type: "post",
    },
  ],

  connections: [
    { source: "first-post", target: "fck-this" },
    { source: "first-post", target: "orangedogs" },
    { source: "first-post", target: "cicacai" },
    { source: "first-post", target: "what-dregs" },
    { source: "fck-this", target: "cicacai" },
    { source: "fck-this", target: "fck-giver" },
    { source: "fck-this", target: "home-archive" },
    { source: "fck-this", target: "monetary-worth" },
    { source: "fck-this", target: "profiler" },
    { source: "cicacai", target: "oh-dear" },
    { source: "cicacai", target: "orangedogs" },
    { source: "orangedogs", target: "servience" },
    { source: "fck-giver", target: "monetary-worth" },
    { source: "monetary-worth", target: "vindication" },
    { source: "are-you-okay", target: "monetary-worth" },
    { source: "are-you-okay", target: "priorities" },
    { source: "oh-dear", target: "home-archive" },
    { source: "oh-dear", target: "fck-giver" },
    { source: "oh-dear", target: "are-you-okay" },
    { source: "welcome-back", target: "fck-this" },
    { source: "welcome-back", target: "home-archive" },
    { source: "welcome-back", target: "pirates" },
    { source: "welcome-back", target: "effort" },
    { source: "welcome-back", target: "evader" },
    { source: "silence", target: "poker" },
    { source: "silence", target: "sleep" },
    { source: "silence", target: "tnr" },
    { source: "heatstroke", target: "his-way" },
    { source: "heatstroke", target: "sleep" },
    { source: "i-was-right", target: "fck-giver" },
    { source: "i-was-right", target: "heatstroke" },
    { source: "priorities", target: "i-was-right" },
    { source: "priorities", target: "today", weak: true },
    { source: "second-thoughts", target: "fck-this", weak: true },
    { source: "second-thoughts", target: "action-p1" },
    { source: "second-thoughts", target: "profiler", weak: true },
    { source: "action-p1", target: "eye-collector" },
    { source: "protests", target: "profiler", weak: true },
    { source: "profiler", target: "servility", weak: true },
    { source: "profiler", target: "poker" },
    { source: "today", target: "welcome-back" },
    { source: "today", target: "servience" },
    { source: "servience", target: "eye-collector", weak: true },
    { source: "servience", target: "a-storm" },
    { source: "servility", target: "second-thoughts" },
    { source: "servility", target: "action-p1" },
    { source: "servility", target: "eye-collector" },
    { source: "vindication", target: "profiler", weak: true },
    { source: "vindication", target: "evader", weak: true },
    { source: "poker", target: "tnr" },
    { source: "evader", target: "welcome-back" },
    { source: "evader", target: "protests", weak: true },
    { source: "evader", target: "a-storm" },
    { source: "evader", target: "what-dregs", weak: true },
    { source: "evader", target: "his-way" },
    { source: "evader", target: "in-shambles" },
    { source: "what-dregs", target: "mew-gane", weak: true },
    { source: "his-way", target: "tnr", weak: true },
    { source: "sleep", target: "his-way" },
    { source: "dreams", target: "second-thoughts" },
    { source: "underscorextwo-tuglemo", target: "today" },
  ],
};
